version: '3.8'

services:
  app:
    build: .
    container_name: a6cars-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb+srv://A6cars:Anu@a6cars.muz7zpm.mongodb.net/?appName=A6cars
      MONGODB_DB_NAME: a6cars
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./backend:/usr/src/app/backend
